name: Pipeline Demo

on:
  push:
    branches:
      - master

jobs:
  test-case:
    runs-on: ubuntu-latest

    steps:
      - name: Take code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: run test cases
        run: |

          pip install -r requirements.txt
          pytest .

  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Take code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@35.175.153.1 << 'EOF'
          set -e  # Exit on any command failure

          if [ -d "/home/ubuntu/Deploy_demo25feb" ]; then
            echo "Directory exists, moving ahead..."
            cd /home/ubuntu/Deploy_demo25feb
            git reset --hard  # Prevent merge conflicts
            git pull origin master
          else
          cd /home/ubuntu
          git clone https://github.com/Iamyashjain/Deploy_demo25feb
          fi

          cd /home/ubuntu/Deploy_demo25feb
          sudo apt update && sudo apt install -y python3 python3-venv python3-pip
          sudo apt install prometheus -y
          # Add Grafana Repository & Install
          echo "Adding Grafana Repository..."
          sudo apt-get install -y software-properties-common
          sudo wget -q -O - https://packages.grafana.com/gpg.key | sudo tee /usr/share/keyrings/grafana.key
          echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
          sudo apt update
          sudo apt install grafana -y
          if [ ! -d "env" ]; then
          python3 -m venv env
          fi


          source env/bin/activate




          python -m ensurepip --default-pip

          docker build -t demo:latest .
          docker run -d -p 8080:8080 demo

          # Upgrade pip and install requirements (bypassing PEP 668 restrictions)
          #  python -m pip install --upgrade pip --break-system-packages
          # python -m pip install -r requirements.txt --break-system-packages



          # Restart Uvicorn
          #pkill uvicorn || true  # Ignore error if Uvicorn is not running

          # Start Uvicorn in the background, redirect logs, and detach process
          #nohup env/bin/uvicorn main:app --host 0.0.0.0 --port 8080 > uvicorn.log 2>&1 & disown



          #sudo systemctl start prometheus
          #sudo systemctl start grafana-server
          #sudo systemctl enable prometheus
          #sudo systemctl enable grafana-server





          EOF
